# -*- coding: utf-8 -*-
"""zadania_13_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nhhsws4efCpDmiOyTj-0EVnV5wpneejI

ZADANIE 1
"""

#ZADANIE 1
class Student:
    def __init__(self, imie, oceny):
        self.imie = imie
        self.oceny = oceny

    def is_passed(self):
        srednia_ocen = sum(self.oceny) / len(self.oceny)
        return srednia_ocen > 50

student1 = Student("Jan", [60, 70, 80])
student2 = Student("Alicja", [40, 30, 20])

wynik1 = student1.is_passed()
wynik2 = student2.is_passed()

print(f"{student1.imie} zdał/a: {wynik1}")
print(f"{student2.imie} zdał/a: {wynik2}")

"""ZADANIE 2

"""

#zadanie 2

class Biblioteka:
    def __init__(self, miasto, ulica, kod_pocztowy, godziny_otwarcia, telefon):
        self.miasto = miasto
        self.ulica = ulica
        self.kod_pocztowy = kod_pocztowy
        self.godziny_otwarcia = godziny_otwarcia
        self.telefon = telefon


    def __str__(self):
        return f"Biblioteka: {self.miasto}, {self.ulica}, {self.kod_pocztowy}\n" \
               f"Godziny otwarcia: {self.godziny_otwarcia}\nTelefon: {self.telefon}\n"


class Pracownik:
    def __init__(self, imie, nazwisko, data_zatrudnienia, data_urodzenia, miasto, ulica, kod_pocztowy, telefon):
        self.imie = imie
        self.nazwisko = nazwisko
        self.data_zatrudnienia = data_zatrudnienia
        self.data_urodzenia = data_urodzenia
        self.miasto = miasto
        self.ulica = ulica
        self.kod_pocztowy = kod_pocztowy
        self.telefon = telefon


    def __str__(self):
        return f"Pracownik: {self.imie} {self.nazwisko}\n" \
               f"Data zatrudnienia: {self.data_zatrudnienia}\nData urodzenia: {self.data_urodzenia}\n" \
               f"Adres: {self.miasto}, {self.ulica}, {self.kod_pocztowy}\nTelefon: {self.telefon}\n"


class Ksiazka:
    def __init__(self, biblioteka, data_publikacji, imie_autora, nazwisko_autora, liczba_stron):
        self.biblioteka = biblioteka
        self.data_publikacji = data_publikacji
        self.imie_autora = imie_autora
        self.nazwisko_autora = nazwisko_autora
        self.liczba_stron = liczba_stron


    def __str__(self):
        return f"Książka: {self.imie_autora} {self.nazwisko_autora}\n" \
               f"Data publikacji: {self.data_publikacji}\n" \
               f"Liczba stron: {self.liczba_stron}\n" \
               f"Biblioteka: {self.biblioteka}\n"


class Zamowienie:
    def __init__(self, pracownik, student, ksiazki, data_zamowienia):
        self.pracownik = pracownik
        self.student = student
        self.ksiazki = ksiazki
        self.data_zamowienia = data_zamowienia


    def __str__(self):
        lista_ksiazek = "\n".join([f"   {ksiazka}" for ksiazka in self.ksiazki])
        return f"Detale zamówienia:\n" \
               f"Pracownik: {self.pracownik}\n" \
               f"Student: {self.student}\n" \
               f"Data zamówienia: {self.data_zamowienia}\n" \
               f"Książki:\n{lista_ksiazek}\n"


biblioteka1 = Biblioteka("Jaworzno", "3 Maja 10", "12345", "9:00 - 17:00", "123-456-789")
biblioteka2 = Biblioteka("Katowice", "Jerozolimska 4", "54321", "10:00 - 18:00", "987-654-321")

pracownik1 = Pracownik("Eder", "Militao", "2022-01-01", "1990-01-01", "Jaworzno", "3 Maja 10", "12345", "43-600")
pracownik2 = Pracownik("Anna", "Lewandowska", "2022-02-01", "1991-01-02", "Katowice", "Jerozolimska 4", "54321", "9999-9")
pracownik3 = Pracownik("Robert", "Lewandowski", "2022-03-01", "1992-01-03", "Jaworzno", "3 Maja 10", "12345", "43-600")

ksiazka1 = Ksiazka(biblioteka1, "2021-01-01", "Adam", "Mickiewicz", 200)
ksiazka2 = Ksiazka(biblioteka1, "2021-02-01", "Henryk", "Sienkiewicz", 150)
ksiazka3 = Ksiazka(biblioteka2, "2021-03-01", "Wisława", "Szymborska", 300)
ksiazka4 = Ksiazka(biblioteka2, "2021-04-01", "J.K", "Rowling", 250)
ksiazka5 = Ksiazka(biblioteka2, "2021-05-01", "Kylian", "Mbappe", 180)

zamowienie1 = Zamowienie(pracownik1, "Student1", [ksiazka1, ksiazka2, ksiazka3], "2022-04-01")
zamowienie2 = Zamowienie(pracownik2, "Student2", [ksiazka4, ksiazka5], "2022-05-01")

print(zamowienie1)
print(zamowienie2)

"""ZADANIE 3"""

#ZADANIE 3
class Nieruchomosc:
    def __init__(self, adres, metraz, cena):
        self.adres = adres
        self.metraz = metraz
        self.cena = cena

    def __str__(self):
        return f"Nieruchomość\nAdres: {self.adres}\nMetraż: {self.metraz} m²\nCena: {self.cena} zł\n"

class Dom(Nieruchomosc):
    def __init__(self, adres, metraz, cena, powierzchnia_dzialki, liczba_pokoi):
        super().__init__(adres, metraz, cena)
        self.powierzchnia_dzialki = powierzchnia_dzialki
        self.liczba_pokoi = liczba_pokoi

    def __str__(self):
        return f"Dom\nAdres: {self.adres}\nMetraż: {self.metraz} m²\n" \
               f"Cena: {self.cena} zł\nPowierzchnia działki: {self.powierzchnia_dzialki} m²\nLiczba pokoi: {self.liczba_pokoi}\n"

class Mieszkanie(Nieruchomosc):
    def __init__(self, adres, metraz, cena, pietro):
        super().__init__(adres, metraz, cena)
        self.pietro = pietro

    def __str__(self):
        return f"Mieszkanie\nAdres: {self.adres}\nMetraż: {self.metraz} m²\n" \
               f"Cena: {self.cena} zł\nPiętro: {self.pietro}\n"

dom1 = Dom("Jaworzno, ul. 3 Maja 10", 150, 500000, 300, 5)
mieszkanie1 = Mieszkanie("Katowice, ul. Jerozolimska 4", 80, 250000, 2)

print(dom1)
print(mieszkanie1)